name: Publish

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-pc-windows-msvc, x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu, x86_64-apple-darwin, aarch64-apple-darwin]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - run: cargo install cargo-xwin

      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Build
        run: |
          npm i
          npm run build --target ${{ matrix.targets }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: OS specific binaries
          path: dist

  deploy:
    # prevents this action from running on forks or pull requests
    if: ${{ github.repository == 'ceifa/tiktoken-node' && github.event_name == 'push' }}

    runs-on: ubuntu-20.04
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: OS specific binaries
          path: dist

      - name: Log files
        run: |
          echo "- Root directory:" && ls
          echo "- Dist directory:" && ls -R dist

      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
